# Generated by Django 6.0.3 on 2026-03-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_member_officer', '0003_amonotification_archive_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amonotification',
            name='notification_type',
            field=models.CharField(choices=[('new_registration', 'New Registration'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('savings_update', 'Savings Update'), ('capital_update', 'Capital Update'), ('action_required', 'Action Required'), ('info', 'Information')], default='info', max_length=20),
        ),
    ]
