"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    # Admin interface (must be before django.contrib.admin)
    'unfold',
    'unfold.contrib.filters',  # Optional: advanced filters
    'unfold.contrib.forms',    # Optional: enhanced forms

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django.contrib.humanize',

    # Local apps
    'users',
    'loans',
    'payments',
    'authentication',
    'reports',
    'bookkeeper',
    'treasurer',
    'credit_committee',
    'applicant',
    'account_member_officer',
    'superadmin',
    # 'members',  # Disabled: duplicate models with applicant app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eloan_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eloan_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # Read DB connection from environment variables so you can point
        # this Django project to any local or remote MySQL/MariaDB server.
        'NAME': config('DB_NAME', default='eloan'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'

# REST Framework and JWT Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Face Verification Settings
FACE_VERIFICATION = {
    'ENABLED': True,
    'AUTO_APPROVE_MAX_DISTANCE': 0.60,  # Cosine distance for auto-approval (<= 0.60 = Verified)
    'REVIEW_MAX_DISTANCE': 0.75,        # Cosine distance ceiling for manual review (0.60–0.75 = Needs Review, > 0.75 = Failed)
    'MODEL': 'ArcFace',  # Face comparison model (ArcFace, Facenet, VGG-Face, etc.)
    'DISTANCE_METRIC': 'cosine',  # Distance metric (cosine, euclidean, euclidean_l2)
    'DETECTOR_BACKEND': 'opencv',  # Face detector (opencv, ssd, dlib, mtcnn, retinaface)
    'UNLIMITED_RETRIES': True,  # Allow unlimited retry attempts
}

# Liveness Detection Settings (MediaPipe)
LIVENESS_DETECTION = {
    'ENABLED': True,
    'MIN_CONFIDENCE_THRESHOLD': 70,  # Minimum confidence % to pass liveness check
    'EAR_THRESHOLD': 0.21,  # Eye Aspect Ratio threshold (below = eyes closed)
    'HEAD_TURN_THRESHOLD': 15,  # Max yaw angle in degrees for natural pose
    'HEAD_NOD_THRESHOLD': 10,  # Max pitch angle in degrees for natural pose
    'DEFAULT_METHOD': 'combined',  # Default detection method: blink, head_turn, combined
}

# OCR Settings
# Leave blank to use the system PATH. Set TESSERACT_CMD in .env when Tesseract
# is installed in a non-standard location.
TESSERACT_CMD = config('TESSERACT_CMD', default='')

# File Encryption Settings
# CRITICAL: ENCRYPTION_KEY must be set in .env — never change it or all encrypted files become unreadable.
# Generate a key once: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"

ENCRYPTION_KEY = config('ENCRYPTION_KEY')  # No default — server will refuse to start if missing

# Cache Configuration (for rate limiting)
# For development: use in-memory cache
# For production: use Redis for better performance and persistence
CACHES = {
    'default': {
        'BACKEND': config(
            'CACHE_BACKEND',
            default='django.core.cache.backends.locmem.LocMemCache'
        ),
        'LOCATION': config('CACHE_LOCATION', default='eloan-cache'),
        # For Redis in production, use:
        # 'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        # 'LOCATION': 'redis://127.0.0.1:6379/1',
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
# For development: emails will be printed to console
# For production: configure SMTP settings in .env file

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'  # Default: print to console
)

# SMTP Configuration (for production with real email sending)
# Set EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend' in .env to use these
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@eloan.com')

# Frontend URL for password reset links
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# CORS Configuration
# Allow requests from the frontend application and mobile app
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:8081,http://localhost:19000,http://localhost:19006',
    cast=Csv()
)
CORS_ALLOW_CREDENTIALS = True

# Django Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "eLoan Administration",
    "SITE_HEADER": "eLoan Admin Console",
    "SITE_URL": "/",
    "SITE_SYMBOL": "account_balance",  # Material Symbols icon in sidebar header
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "development",
    "DASHBOARD_CALLBACK": None,
    "STYLES": [
        lambda request: "/static/css/custom-admin.css",
    ],
    "SCRIPTS": [],
    # eLoan brand color scale — navy #02327a as the 700 anchor
    "COLORS": {
        "primary": {
            "50":  "236 244 255",
            "100": "213 232 255",
            "200": "172 209 255",
            "300": "108 173 255",
            "400": "52  126 246",
            "500": "14  88  210",
            "600": "8   65  175",
            "700": "2   50  122",   # #02327a — eLoan brand
            "800": "1   38  95",
            "900": "1   28  70",
            "950": "1   18  46",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "User Management",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": lambda request: "/admin/users/user/",
                    },
                    {
                        "title": "Roles",
                        "icon": "badge",
                        "link": lambda request: "/admin/users/role/",
                    },
                    {
                        "title": "Pending Approval",
                        "icon": "pending_actions",
                        "link": lambda request: "/admin/users/user/?account_status__exact=pending",
                    },
                ],
            },
            {
                "title": "Member Management",
                "separator": True,
                "items": [
                    {
                        "title": "All Members",
                        "icon": "people",
                        "link": lambda request: "/admin/applicant/member/",
                    },
                    {
                        "title": "Savings Records",
                        "icon": "savings",
                        "link": lambda request: "/admin/applicant/savings/",
                    },
                    {
                        "title": "Shared Capital",
                        "icon": "account_balance",
                        "link": lambda request: "/admin/applicant/sharedcapital/",
                    },
                ],
            },
            {
                "title": "Loan Management",
                "separator": True,
                "items": [
                    {
                        "title": "Loan Applications",
                        "icon": "description",
                        "link": lambda request: "/admin/loans/loanapplication/",
                    },
                    {
                        "title": "Loan Types",
                        "icon": "category",
                        "link": lambda request: "/admin/loans/loantype/",
                    },
                    {
                        "title": "Application Status",
                        "icon": "flag",
                        "link": lambda request: "/admin/loans/applicationstatus/",
                    },
                    {
                        "title": "Documents",
                        "icon": "folder",
                        "link": lambda request: "/admin/loans/loandocument/",
                    },
                ],
            },
            {
                "title": "Payments",
                "separator": True,
                "items": [
                    {
                        "title": "All Payments",
                        "icon": "payments",
                        "link": lambda request: "/admin/payments/payment/",
                    },
                ],
            },
            {
                "title": "Disciplinary",
                "separator": True,
                "items": [
                    {
                        "title": "Violations",
                        "icon": "gavel",
                        "link": lambda request: "/admin/superadmin/violation/",
                    },
                    {
                        "title": "Disciplinary Actions",
                        "icon": "policy",
                        "link": lambda request: "/admin/superadmin/disciplinaryaction/",
                    },
                    {
                        "title": "Termination Records",
                        "icon": "person_remove",
                        "link": lambda request: "/admin/superadmin/terminationrecord/",
                    },
                ],
            },
            {
                "title": "Reports & Analytics",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": lambda request: "/admin/reports/dashboard/",
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": ["users.user"],
            "items": [
                {
                    "title": "All Users",
                    "link": lambda request: "/admin/users/user/",
                },
                {
                    "title": "Pending Approval",
                    "link": lambda request: "/admin/users/user/?account_status__exact=pending",
                },
                {
                    "title": "Approved",
                    "link": lambda request: "/admin/users/user/?account_status__exact=approved",
                },
                {
                    "title": "Rejected",
                    "link": lambda request: "/admin/users/user/?account_status__exact=rejected",
                },
                {
                    "title": "Suspended",
                    "link": lambda request: "/admin/users/user/?status__exact=suspended",
                },
            ],
        },
        {
            "models": ["superadmin.violation"],
            "items": [
                {
                    "title": "All Violations",
                    "link": lambda request: "/admin/superadmin/violation/",
                },
                {
                    "title": "Open",
                    "link": lambda request: "/admin/superadmin/violation/?status__exact=open",
                },
                {
                    "title": "Escalated",
                    "link": lambda request: "/admin/superadmin/violation/?status__exact=escalated",
                },
                {
                    "title": "Resolved",
                    "link": lambda request: "/admin/superadmin/violation/?status__exact=resolved",
                },
            ],
        },
    ],
}
