# Generated by Django 6.0.3 on 2026-03-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_remove_completed_loan_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the Credit Committee approved this loan', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='When the Treasurer released (disbursed) the funds', null=True),
        ),
    ]
